DinoMVC/Models/Dino.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DinoMVC.Models
{
    public class Dino
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Period { get; set; }

        [Required]
        public string Diet { get; set; }

    }
}

DinoMVC/Models/DinoDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DinoMVC.Models
{
    public class DinoDbContext : DbContext
    {
        public DinoDbContext(DbContextOptions<DinoDbContext> opt) : base(opt)
        {

        }
        public DbSet<Dino> Dino { get; set; }
    }
}

DinoMVC/Models/ErrorViewModel.cs
using System;

namespace DinoMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DinoMVC/Controllers/DinoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DinoMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DinoMVC.Controllers
{
    public class DinoController : Controller
    {
        private readonly DinoDbContext _db;
        
        [BindProperty]
        public Dino Dino { get; set; }
        
        public DinoController(DinoDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult ViewDino(int id)
        {
            Dino = _db.Dino.FirstOrDefault(d => d.Id == id);
            if (Dino == null)
            {
                return NotFound();
            }
            return View(Dino);
        }

        public IActionResult Upsert(int? id)
        {
            Dino = new Dino();
            if (id == null)
            {
                return View(Dino);
            }
            Dino = _db.Dino.FirstOrDefault(d => d.Id == id);
            if (Dino == null)
            {
                return NotFound();
            }
            return View(Dino);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert()
        {
            //Dino = new Dino();
            if (ModelState.IsValid)
            {
                if (Dino.Id == 0)
                {
                    _db.Dino.Add(Dino);
                }
                else
                {
                    _db.Dino.Update(Dino);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Dino);
        }
        #region API Calls
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _db.Dino.ToListAsync() });
        }

        [HttpGet]
        public async Task<IActionResult> Get(int id)
        {
            var D = await _db.Dino.FirstOrDefaultAsync(d => d.Id == id);
            if (D != null)
            {
                return Json(new { data = await _db.Dino.FirstOrDefaultAsync(d => d.Id == id)});
            }
            return Json(new { success = false, message = "Error getting Dino with id: "+id });
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var D = await _db.Dino.FirstOrDefaultAsync(d => d.Id == id);
            if (D != null)
            {
                _db.Dino.Remove(D);
                await _db.SaveChangesAsync();
                return Json(new { success = true, message = "Delete successful" });
            }
            return Json(new { success = false, message = "Error while Deleting" });
        }
        #endregion

    }
}

DinoMVC/Controllers/DinoGameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Data;
using System.Web;
using DinoMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace DinoMVC.Controllers
{
    public class DinoGameController : Controller
    {
        private readonly DinoDbContext _db;

        [BindProperty]
        public Dino Dino { get; set; }
        public List<Dino> Dinos { get; set; }

        public DinoGameController(DinoDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            //Dino = _db.Dino.FirstOrDefault(d => d.Id == 1);
            Dinos = _db.Dino.ToList();
            
            return View(Dinos);
        }
        public JsonResult GetAllDino()
        {
            Dinos = _db.Dino.ToList();
            return Json(Dinos);
        }
    }
}

DinoMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DinoMVC.Models;

namespace DinoMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DinoMVC/Views/Dino/Index.cshtml
@{
    ViewData["Title"] = "Dino";
}
<br />
<div class="container row p-0 m-0">
    <div class="col-8">
        <h2 class="test-info">Dinosaurs</h2>
    </div>
    <div class="col-4">
        <a asp-action="Upsert" asp-controller="Dino" class="btn btn-primary form-control text-white"> Add New Dino</a>
    </div>
    <div class="col-12 border p-3">
        <table id="DT_load" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Period</th>
                    <th>Diet</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
</div>
@section Scripts{
    <script src="~/js/dinosList.js"></script>
}

DinoMVC/Views/Dino/Upsert.cshtml
@model DinoMVC.Models.Dino

<br/>
<h2 class="text-info">@(Model.Id !=0 ? "Edit":"Create") Dino</h2>
<br/>

<div class="border container" style="padding:40px;">
    <form method="post">
        @if (Model.Id != 0)
        {
            <input type="hidden" asp-for="Id" />
        }
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="@Model.Name"></label>
            </div>
            <div class="col-8">
                <input asp-for="@Model.Name" class="form-control" />
            </div>
            <span asp-validation-for="@Model.Name" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="@Model.Period"></label>
            </div>
            <div class="col-8 row">
                <div class="col-4">
                    <input asp-for="@Model.Period" type="radio" name="period" value="Cretaceous">
                    <label>Cretaceous</label>
                </div>
                <div class="col-4">
                    <input asp-for="@Model.Period" type="radio" name="period" value="Jurassic">
                    <label>Jurassic</label>
                </div>
                <div class="col-4">
                    <input asp-for="@Model.Period" type="radio" name="period" value="Triassic" checked="checked">
                    <label>Triassic</label><br>
                </div>
            </div>
            <span asp-validation-for="@Model.Period" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="@Model.Diet"></label>
            </div>
            <div class="col-8 row">
                <div class="col-4">
                    <input asp-for="@Model.Diet" type="radio" name="diet" value="Herbivore">
                    <label>Herbivore</label>
                </div>
                <div class="col-4">
                    <input asp-for="@Model.Diet" type="radio" name="diet" value="Omnivore">
                    <label>Omnivore</label>
                </div>
                <div class="col-4">
                    <input asp-for="@Model.Diet" type="radio" name="diet" value="Carnivore" checked="checked">
                    <label>Carnivore</label><br>
                </div>
            </div>
            <span asp-validation-for="@Model.Diet" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-4 offset-3">
                <button type="submit" class="btn btn-primary form-control">
                    @(Model.Id !=0 ? "Update":"Create")
                </button>
            </div>
            <div class="col-5">
                <a asp-action="Index" class="btn btn-success form-control"> Back to List </a>
            </div>
        </div>
    </form>
</div>
@section scripts{
<partial name="_ValidationScriptsPartial"/>
}

DinoMVC/Views/Dino/ViewDino.cshtml
@model DinoMVC.Models.Dino

<br />
<h2 class="text-info" style="border-bottom: 1px solid #000;">@(Model.Name) Dino</h2>
<br />

<div class="border container" style="padding:40px;">
    <div class="form-group row">
        <div class="col-4">
            <label>Dino Id :</label>
        </div>
        <div class="col-8">
            <label>@Model.Id</label>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-4">
            <label>Time Period :</label>
        </div>
        <div class="col-8">
            <label>@Model.Period</label>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-4">
            <label>Diet :</label>
        </div>
        <div class="col-8">
            <label>@Model.Diet</label>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-5">
            <a asp-action="Index" class="btn btn-success form-control"> Back to List </a>
        </div>
    </div>
</div>

DinoMVC/Views/DinoGame/Index.cshtml
@{
    ViewData["Title"] = "Dino Game";
    Random _random = new Random(); 
    int num = _random.Next(Model.Count);
}
@model List<DinoMVC.Models.Dino>  
<br />
<br />
<br />
<div class="border p-3 form-group row">
    <div class="col-4 offset-4" id="container">
        <canvas id="game" width="320" height="480"></canvas>
    </div>
    <div class="col-4">
        <h1>Get answers right to get ammo and save the Dinosaurs</h1>
        <label id="DinoName"></label>
        <br />
        <br />
        <button id="Button1" class="btn btn-success">Herbivore</button>
        <button id="Button2" class="btn btn-info">Omnivore</button>
        <button id="Button3" class="btn btn-danger">Carnivore</button>
        <br />
        <br />
        <label id="isCorrect"></label>
    </div>
</div>

@section Scripts{
    <script src='~/js/dinoGameEngine.js'></script>
    <script src='~/js/dinoGame.js'></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript">var numb = @num;</script>
    <script src="~/js/dinoQuiz.js"></script>
}

DinoMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Welcome to Dino";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Dino</h1>
    <img class="col-9" src="~/img/dinos.jpg" alt="Dinosaurs" width="700" height="500">
</div>

DinoMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DinoMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="shortcut icon" href="~/dinoicon.ico" type="image/x-icon" />

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DinoMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dino" asp-action="Index">DinoList</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DinoGame" asp-action="Index">Dino Game</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - DinoMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript" src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>